version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - dbpersistent:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=phpbali
      - MYSQL_ROOT_PASSWORD=root
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/usr/web/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
      - db
    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - "8080:8080"
  app:
    build:
      context: .
    volumes:
        - .:/usr/web/
    restart: unless-stopped
    links:
      - db
volumes:
  dbpersistent:
