name: CI-CD PHPBali

on: push

jobs:
  compile-assets:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Build jS
      - name: Yarn build
        run: |
          yarn install
          yarn prod
          cat public/mix-manifest.json # see version in log
      - name: Upload compile assets
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
          extension-csv: mbstring, bmath
      - name: Composer install
        run: composer install
      - name: Generate artisan key
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: ./vendor/bin/phpunit
